### ISSUE TITLE
Different results in CI vs local

### ISSUE THREAD

**Issue by jsjoeio** [actionsx/prettier#101]
Hey! 👋🏼

For some reason, when I run this action in CI vs locally, I get different results: 

https://github.com/coder/code-server/actions/runs/3155272047/jobs/5133765429#step:3:100

local

<img width="773" alt="image" src="https://user-images.githubusercontent.com/3806031/193160015-5373b9d6-a2d0-4373-a20e-21021c4891ba.png">

I cannot figure out what's wrong. Any ideas?

Relevant PR: https://github.com/coder/code-server/pull/5605

**Comment by phuctm97** [comment]
A fix has been updated now. Can you try to rerun the workflow?

**Comment by jsjoeio** [comment]
I think it's good now! Thank you!
