### ISSUE TITLE
Add comparison to other prettier actions

### ISSUE THREAD

**Issue by IlanCosman** [actionsx/prettier#25]
Specifically [creyD/prettier_action](https://github.com/creyD/prettier_action). As far as I can tell the main difference is using JS and not docker/shell. Yours runs faster but his seems to be more full-featured. I think that adding a comparison to your readme would be worthwhile to show your advantages/disadvantages.

**Comment by phuctm97** [comment]
Hey @IlanCosman, thanks for the recommendation, definitely see the need, but my plan is to let the community use and report issues, then either fix it or update the docs to show disadvantages. There's no issue so far. Would really appreciate if you can create a PR with some suggested comparisons though!

**Comment by phuctm97** [comment]
Close due to inactivity
